@startuml packages_pingpy_output
set namespaceSeparator none
package "pingpy.output" as pingpy.output {
}
package "pingpy.output.UICorner" as pingpy.output.UICorner {
}
package "pingpy.output.bumper" as pingpy.output.bumper {
}
package "pingpy.output.linearActuator" as pingpy.output.linearActuator {
}
package "pingpy.output.output" as pingpy.output.output {
}
package "pingpy.output.player" as pingpy.output.player {
}
package "pingpy.output.playerLedStrip" as pingpy.output.playerLedStrip {
}
package "pingpy.output.speaker" as pingpy.output.speaker {
}
pingpy.output --> pingpy.output
pingpy.output.output --> pingpy.output.UICorner
pingpy.output.output --> pingpy.output.player
pingpy.output.output --> pingpy.output.speaker
pingpy.output.player --> pingpy.output.bumper
pingpy.output.player --> pingpy.output.linearActuator
pingpy.output.player --> pingpy.output.playerLedStrip
@enduml
