@startuml packages_pingpy_serialHard
set namespaceSeparator none
package "pingpy.serialHard" as pingpy.serialHard {
}
package "pingpy.serialHard.ESP32" as pingpy.serialHard.ESP32 {
}
package "pingpy.serialHard.UICorner" as pingpy.serialHard.UICorner {
}
package "pingpy.serialHard.controller" as pingpy.serialHard.controller {
}
package "pingpy.serialHard.serialCom" as pingpy.serialHard.serialCom {
}
pingpy.serialHard --> pingpy.serialHard.ESP32
pingpy.serialHard --> pingpy.serialHard.UICorner
pingpy.serialHard --> pingpy.serialHard.controller
pingpy.serialHard.ESP32 --> pingpy.serialHard.serialCom
pingpy.serialHard.UICorner --> pingpy.serialHard.serialCom
pingpy.serialHard.controller --> pingpy.serialHard.serialCom
@enduml
