@startuml classes_pingpy_input
set namespaceSeparator none
class "BeamSwitchInput" as pingpy.input.beamSwitch.BeamSwitchInput {
  state : NoneType
}
class "GameController3ButtonInput" as pingpy.input.gameController3Button.GameController3ButtonInput {
  countButton : int
  left : bool
  right : bool
  shoot : bool
}
class "GameControllerInput" as pingpy.input.gameController.GameControllerInput {
  inAction : bool
}
class "Input" as pingpy.input.input.Input {
  UICorner
  player
}
class "LinearActuatorInput" as pingpy.input.linearActuator.LinearActuatorInput {
  currentPose : NoneType
  leftLimit : NoneType
  moving : bool
  rightLimit : NoneType
}
class "PlayerInput" as pingpy.input.player.PlayerInput {
  beamSwitch
  gameController
  linearActuator
  pointCounter : int
  usb : ControllerSerial
}
class "UICornerInput" as pingpy.input.UICorner.UICornerInput {
  level : NoneType
  light : NoneType
  modeDec : NoneType
  modeInc : NoneType
  modePush : NoneType
  modeRelease : NoneType
  resetLongPress : NoneType
  resetPush : NoneType
  resetRelease : NoneType
  resetShortPress : NoneType
  volume : NoneType
}
pingpy.input.gameController3Button.GameController3ButtonInput --|> pingpy.input.gameController.GameControllerInput
pingpy.input.UICorner.UICornerInput --* pingpy.input.input.Input : UICorner
pingpy.input.beamSwitch.BeamSwitchInput --* pingpy.input.player.PlayerInput : beamSwitch
pingpy.input.gameController.GameControllerInput --* pingpy.input.player.PlayerInput : gameController
pingpy.input.linearActuator.LinearActuatorInput --* pingpy.input.player.PlayerInput : linearActuator
pingpy.input.player.PlayerInput --* pingpy.input.input.Input : 4 players
@enduml
