@startuml classes_pingpy_serialHard
set namespaceSeparator none
class "ControllerSerial" as pingpy.serialHard.controller.ControllerSerial {
  controllerInput
  read(controllerInput, controllerOutput)
  stopOnDisconnect(controllerOutput)
}
class "ESP32Serial" as pingpy.serialHard.ESP32.ESP32Serial {
  key_values : list
  process_key_values(input_ptr)
  read(input_ptr)
  setup(output_ptr)
  write(output_ptr, input_ptr)
}
class "SerialCom" as pingpy.serialHard.serialCom.SerialCom {
  baudrate
  connected : bool
  failed_attempts : int
  port : NoneType
  queue : list
  ser : NoneType, Serial
  symlink
  timeout
  consume_older_data()
  read_data_task(onDisconnect, args)
  send_data(data)
  setup()
  stop_reading()
}
class "UICornerSerial" as pingpy.serialHard.UICorner.UICornerSerial {
  lastResetPressedTime : NoneType
  resetButtonState : NoneType, bool
  manageResetButton(input_ptr, output_ptr)
  read(input_ptr, output_ptr)
  setup(output_ptr)
  write(output_ptr, input_ptr)
}
pingpy.serialHard.ESP32.ESP32Serial --|> pingpy.serialHard.serialCom.SerialCom
pingpy.serialHard.UICorner.UICornerSerial --|> pingpy.serialHard.serialCom.SerialCom
pingpy.serialHard.controller.ControllerSerial --|> pingpy.serialHard.serialCom.SerialCom
@enduml
