@startuml packages_pingpy_hardware
set namespaceSeparator none
package "pingpy.hardware" as pingpy.hardware {
}
package "pingpy.hardware.autoSwitch" as pingpy.hardware.autoSwitch {
}
package "pingpy.hardware.gpioMock" as pingpy.hardware.gpioMock {
}
package "pingpy.hardware.ledStrip" as pingpy.hardware.ledStrip {
}
package "pingpy.hardware.rpi_ws281xMock" as pingpy.hardware.rpi_ws281xMock {
}
pingpy.hardware --> pingpy.hardware.autoSwitch
pingpy.hardware --> pingpy.hardware.ledStrip
@enduml
