@startuml packages_pingpy
set namespaceSeparator none
package "pingpy" as pingpy {
}
package "pingpy.config" as pingpy.config {
}
' package "pingpy.config.config" as pingpy.config.config {
' }
package "pingpy.debug" as pingpy.debug {
}
' package "pingpy.debug.logFile" as pingpy.debug.logFile {
' }
package "pingpy.gameMode" as pingpy.gameMode {
}
' package "pingpy.gameMode.atYourCommand" as pingpy.gameMode.atYourCommand {
' }
' package "pingpy.gameMode.battleRoyale" as pingpy.gameMode.battleRoyale {
' }
' package "pingpy.gameMode.gameMode" as pingpy.gameMode.gameMode {
' }
' package "pingpy.gameMode.lightTracker" as pingpy.gameMode.lightTracker {
' }
' package "pingpy.gameMode.memoChain" as pingpy.gameMode.memoChain {
' }
' package "pingpy.gameMode.pingGame" as pingpy.gameMode.pingGame {
' }
' package "pingpy.gameMode.redLightGreenLight" as pingpy.gameMode.redLightGreenLight {
' }
' package "pingpy.gameMode.sandBox" as pingpy.gameMode.sandBox {
' }
' package "pingpy.gameMode.waitingRoom" as pingpy.gameMode.waitingRoom {
' }
package "pingpy.gitUpdate" as pingpy.gitUpdate {
}
' package "pingpy.gitUpdate.hotspot" as pingpy.gitUpdate.hotspot {
' }
package "pingpy.hardware" as pingpy.hardware {
}
' package "pingpy.hardware.autoSwitch" as pingpy.hardware.autoSwitch {
' }
' package "pingpy.hardware.gpioMock" as pingpy.hardware.gpioMock {
' }
' package "pingpy.hardware.ledStrip" as pingpy.hardware.ledStrip {
' }
' package "pingpy.hardware.rpi_ws281xMock" as pingpy.hardware.rpi_ws281xMock {
' }
package "pingpy.input" as pingpy.input {
}
' package "pingpy.input.UICorner" as pingpy.input.UICorner {
' }
' package "pingpy.input.beamSwitch" as pingpy.input.beamSwitch {
' }
' package "pingpy.input.gameController" as pingpy.input.gameController {
' }
' package "pingpy.input.gameController3Button" as pingpy.input.gameController3Button {
' }
' package "pingpy.input.input" as pingpy.input.input {
' }
' package "pingpy.input.linearActuator" as pingpy.input.linearActuator {
' }
' package "pingpy.input.player" as pingpy.input.player {
' }
package "pingpy.output" as pingpy.output {
}
' package "pingpy.output.UICorner" as pingpy.output.UICorner {
' }
' package "pingpy.output.bumper" as pingpy.output.bumper {
' }
' package "pingpy.output.linearActuator" as pingpy.output.linearActuator {
' }
' package "pingpy.output.output" as pingpy.output.output {
' }
' package "pingpy.output.player" as pingpy.output.player {
' }
' package "pingpy.output.playerLedStrip" as pingpy.output.playerLedStrip {
' }
' package "pingpy.output.speaker" as pingpy.output.speaker {
' }
package "pingpy.ping" as pingpy.ping {
}
package "pingpy.serialHard" as pingpy.serialHard {
}
' package "pingpy.serialHard.ESP32" as pingpy.serialHard.ESP32 {
' }
' package "pingpy.serialHard.UICorner" as pingpy.serialHard.UICorner {
' }
' package "pingpy.serialHard.controller" as pingpy.serialHard.controller {
' }
' package "pingpy.serialHard.serialCom" as pingpy.serialHard.serialCom {
' }
pingpy --> pingpy.debug
pingpy --> pingpy.gameMode
pingpy --> pingpy.gitUpdate
pingpy --> pingpy.hardware
pingpy --> pingpy.input
pingpy --> pingpy.output
pingpy --> pingpy.ping
pingpy --> pingpy.serialHard
' pingpy.debug --> pingpy.debug.logFile
' pingpy.debug.logFile --> pingpy.config.config
' pingpy.gameMode --> pingpy.gameMode.redLightGreenLight
' pingpy.gameMode --> pingpy.gameMode.waitingRoom
' pingpy.gameMode.atYourCommand --> pingpy.gameMode.gameMode
' pingpy.gameMode.battleRoyale --> pingpy.gameMode.gameMode
' pingpy.gameMode.gameMode --> pingpy.input.input
' pingpy.gameMode.gameMode --> pingpy.output.output
' pingpy.gameMode.lightTracker --> pingpy.debug.logFile
' pingpy.gameMode.lightTracker --> pingpy.gameMode.gameMode
' pingpy.gameMode.lightTracker --> pingpy.input.input
' pingpy.gameMode.lightTracker --> pingpy.output.output
' pingpy.gameMode.memoChain --> pingpy.gameMode.gameMode
' pingpy.gameMode.pingGame --> pingpy.gameMode.gameMode
' pingpy.gameMode.redLightGreenLight --> pingpy.config.config
' pingpy.gameMode.redLightGreenLight --> pingpy.debug
' pingpy.gameMode.redLightGreenLight --> pingpy.gameMode.gameMode
' pingpy.gameMode.sandBox --> pingpy.gameMode.gameMode
' pingpy.gameMode.waitingRoom --> pingpy.config.config
' pingpy.gameMode.waitingRoom --> pingpy.debug
' pingpy.gameMode.waitingRoom --> pingpy.gameMode.gameMode
' pingpy.gitUpdate --> pingpy.config.config
' pingpy.gitUpdate --> pingpy.debug
' pingpy.gitUpdate --> pingpy.gitUpdate.hotspot
' pingpy.gitUpdate.hotspot --> pingpy.config.config
' pingpy.gitUpdate.hotspot --> pingpy.debug
' pingpy.hardware --> pingpy.config.config
' pingpy.hardware --> pingpy.hardware.autoSwitch
' pingpy.hardware --> pingpy.hardware.ledStrip
' pingpy.hardware.autoSwitch --> pingpy.debug.logFile
' pingpy.hardware.gpioMock --> pingpy.debug
' pingpy.hardware.ledStrip --> pingpy.debug
' pingpy.hardware.rpi_ws281xMock --> pingpy.debug
' pingpy.input --> pingpy.input.input
' pingpy.input.UICorner --> pingpy.debug
' pingpy.input.beamSwitch --> pingpy.debug
' pingpy.input.gameController --> pingpy.debug
' pingpy.input.gameController3Button --> pingpy.debug
' pingpy.input.gameController3Button --> pingpy.input.gameController
' pingpy.input.input --> pingpy.config.config
' pingpy.input.input --> pingpy.debug
' pingpy.input.input --> pingpy.input.UICorner
' pingpy.input.input --> pingpy.input.player
' pingpy.input.linearActuator --> pingpy.debug
' pingpy.input.player --> pingpy.config.config
' pingpy.input.player --> pingpy.debug
' pingpy.input.player --> pingpy.input.beamSwitch
' pingpy.input.player --> pingpy.input.gameController
' pingpy.input.player --> pingpy.input.linearActuator
' pingpy.input.player --> pingpy.serialHard.controller
' pingpy.output --> pingpy.output.output
' pingpy.output.UICorner --> pingpy.debug
' pingpy.output.bumper --> pingpy.debug
' pingpy.output.linearActuator --> pingpy.debug
' pingpy.output.output --> pingpy.debug
' pingpy.output.output --> pingpy.output.UICorner
' pingpy.output.output --> pingpy.output.player
' pingpy.output.output --> pingpy.output.speaker
' pingpy.output.player --> pingpy.debug
' pingpy.output.player --> pingpy.output.bumper
' pingpy.output.player --> pingpy.output.linearActuator
' pingpy.output.player --> pingpy.output.playerLedStrip
' pingpy.output.playerLedStrip --> pingpy.debug
' pingpy.output.speaker --> pingpy.debug
pingpy.ping --> pingpy
' pingpy.ping --> pingpy.config.config
' pingpy.ping --> pingpy.hardware.ledStrip
' pingpy.ping --> pingpy.input.gameController3Button
' pingpy.serialHard --> pingpy.serialHard.ESP32
' pingpy.serialHard --> pingpy.serialHard.UICorner
' pingpy.serialHard --> pingpy.serialHard.controller
' pingpy.serialHard.ESP32 --> pingpy.config.config
' pingpy.serialHard.ESP32 --> pingpy.debug
' pingpy.serialHard.ESP32 --> pingpy.serialHard.serialCom
' pingpy.serialHard.UICorner --> pingpy.config.config
' pingpy.serialHard.UICorner --> pingpy.debug
' pingpy.serialHard.UICorner --> pingpy.serialHard.serialCom
' pingpy.serialHard.controller --> pingpy.config.config
' pingpy.serialHard.controller --> pingpy.debug
' pingpy.serialHard.controller --> pingpy.serialHard.serialCom
' pingpy.serialHard.serialCom --> pingpy.config.config
' pingpy.serialHard.serialCom --> pingpy.debug
@enduml
